---
- name: Настройка Ingress
  hosts: k8s_master
  become: yes
  tasks:
    - name: Создание Ingress ресурса (через heredoc)
      shell: |
        cat <<EOF | microk8s kubectl apply -n lab-ns -f -
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: lab-ingress
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
        spec:
          rules:
          - host: helloworld.k8s.cluster
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: books-service
                    port:
                      number: 80
          - host: myapp.k8s.cluster
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: hello-service
                    port:
                      number: 80
          - host: dashboard.k8s.cluster
            http:
              paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: kubernetes-dashboard
                    port:
                      number: 443
        EOF
      args:
        executable: /bin/bash