---
- name: Установка и настройка MicroK8s
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Установка snapd
      apt:
        name: snapd
        state: present

    - name: Установка MicroK8s
      snap:
        name: microk8s
        channel: 1.28/stable
        classic: yes

    - name: Добавление пользователя в группу microk8s
      user:
        name: ubuntu
        groups: microk8s
        append: yes

    - name: Ожидание готовности MicroK8s
      command: microk8s status --wait-ready
      register: microk8s_status
      changed_when: false
      retries: 10
      delay: 10

    - name: Создание псевдонимов (только на мастере)
      copy:
        dest: /home/ubuntu/.bash_aliases
        content: |
          alias kubectl='microk8s kubectl'
          alias helm='microk8s helm'
      when: "'k8s_master' in group_names"